{{- if .Values.config.typha.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: typha-cpha
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments/scale"]
    verbs: ["get", "update"]
{{- end }}
