image:
  repository: eu.gcr.io/gardener-project/gardener/extensions/networking-calico
  tag: latest
  pullPolicy: IfNotPresent

resources: {}
vpa:
  enabled: true
# resourcePolicy:
#   minAllowed:
#     cpu: 100m
#     memory: 128Mi

# imageVectorOverwrite: |
#   images:
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.0"
#     version: 1.11.x
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.1"
#     version: ">= 1.12"
#   ...

controller:
  concurrentSyncs: 5
  healthcheck:
    concurrentSyncs: 5
  ignoreOperationAnnotation: false

leaderElection:
  resourceLock: leases

config:
  clientConnection:
    acceptContentTypes: application/json
    contentType: application/json
    qps: 100
    burst: 130
  egressFilter:
    enabled: false
    defaultContentConfigMapName: egress-filter-default-content-configmap
    defaultDeploymentReplicaCount: 1
    defaultFilterSet: {}
#   - network: 1.2.3.4/32
#     policy: BLOCK_ACCESS
#   - network: 4.3.2.1/32
#     policy: BLOCK_ACCESS
    deployDefaultContentConfigMap: true
    deployDefaultDeployment: true
    deployDefaultDownloaderConfigMap: true
    deployDefaultDownloaderSecret: true
    deployDefaultService: true
    downloaderSecretName: egress-filter-default-downloader-secret
    downloaderConfigMapName: egress-filter-default-downloader
    downloadSchedule: "0 0 * * *"
