{{- if .Values.config.egressFilter.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: egress-filter-refresher
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: egress-filter-refresher
          containers:
          - name: egress-filter-refresher
            image: docktofuture/egress-filter-refresher:v1
            imagePullPolicy: IfNotPresent
            env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: egress-filter-fetch-credentials
                  key: cliendID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: egress-filter-fetch-credentials
                  key: clientSecret
            - name: LISTFILE
              value: /tmp/list.json
            volumeMounts:
              - mountPath: /downloader
                name: egress-filter-downloader
          volumes:
            - name: egress-filter-downloader
              configMap:
                name: egress-filter-downloader
                defaultMode: 0777
          restartPolicy: OnFailure
{{- end }}
