{{- if .Values.config.egressFilter.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: egress-filter-refresher
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.config.egressFilter.downloadSchedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: egress-filter-refresher
          containers:
          - name: egress-filter-refresher
            image: eu.gcr.io/gardener-project/gardener/egress-filter-refresher:0.2.0
            imagePullPolicy: IfNotPresent
            env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LISTFILE
              value: /tmp/list.json
            envFrom:
            - secretRef:
                name: {{ .Values.config.egressFilter.downloaderSecretName }}
            volumeMounts:
              - mountPath: /downloader
                name: egress-filter-downloader
          volumes:
            - name: egress-filter-downloader
              configMap:
                name: {{ .Values.config.egressFilter.downloaderConfigMapName }}
                defaultMode: 0777
          restartPolicy: OnFailure
{{- end }}
