apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: egress-filter-refresher
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - egress-filter-list
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
