{{- if not .Values.pspDisabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gardener.cloud:psp:calico
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:psp:kube-system:calico
subjects:
- kind: ServiceAccount
  name: calico-node
  namespace: kube-system
{{- end }}
