{{- if .Values.vpa.enabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: calico-node
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: calico-node
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      minAllowed:
        memory: 100Mi
      maxAllowed:
        cpu: 4
        memory: 10G
      controlledValues: RequestsOnly
{{- end }}
