---
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-node-vertical-autoscaler
  namespace: kube-system
data:
  node-autoscaler: |-
    {
      "calico-node": {
        "requests": {
          "cpu": {
            "base": "120m",
            "step": "80m",
            "nodesPerStep": 10,
            "max": "800m"
          },
          "memory": {
            "base": "50Mi",
            "step": "50Mi",
            "nodesPerStep": 10,
            "max": "1400Mi"
          }
        },
        "limits": {
          "cpu": {
            "base": "320m",
            "step": "80m",
            "nodesPerStep": 10,
            "max": "800m"
          },
          "memory": {
            "base": "650Mi",
            "step": "50Mi",
            "nodesPerStep": 10,
            "max": "1400Mi"
          }
        }
      }
    }
