{{- if and (.Values.config.typha.enabled) (not .Values.pspDisabled) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener.cloud:psp:kube-system:calico-typha
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - gardener.kube-system.calico-typha
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{- end }}
