{{- if .Values.config.typha.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-typha-vertical-autoscaler
  namespace: kube-system
data:
  typha-autoscaler: |-
    {
      "calico-typha": {
        "requests": {
          "cpu": {
            "base": "180m",
            "step": "140m",
            "nodesPerStep": 17,
            "max": "1000m"
          },
          "memory": {
            "base": "180Mi",
            "step": "70Mi",
            "nodesPerStep": 17,
            "max": "2000Mi"
          }
        },
        "limits": {
          "cpu": {
            "base": "500m",
            "step": "170m",
            "nodesPerStep": 17,
            "max": "1000m"
          },
          "memory": {
            "base": "600Mi",
            "step": "85Mi",
            "nodesPerStep": 17,
            "max": "2000Mi"
          }
        }
      }
    }
{{- end }}
