{{- if .Values.config.egressFilter.enabled }}
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: egress-filter-policy
spec:
  order: 100
  types:
  - Egress
  egress:
  - action: Deny
    destination:
      selector: egress == 'filter'
  - action: Allow
    destination:
      nets:
      - 0.0.0.0/0
{{- end }}
