{{- if .Values.config.egressFilter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: egress-filter
  namespace: kube-system
type: Opaque
stringData:
  ipv4-list: |
{{- if .Values.egressFilterSet }}
{{ toYaml .Values.egressFilterSet.ipv4 | indent 4 }}
{{- end }}
  ipv6-list: |
{{- if .Values.egressFilterSet }}
{{ toYaml .Values.egressFilterSet.ipv6 | indent 4 }}
{{- end }}
{{- end }}
