global:
  podCIDR: ""
  #nodeCIDR: "" # Only set when available
  overlayEnabled: ""
  snatToUpstreamDNSEnabled: ""
config:
  veth_mtu: 1440
  backend: bird
  monitoring:
    enabled: true
    felixMetricsPort: 9091
    typhaMetricsPort: 9093
  ipam:
    type: "host-local"
    # subnet: "usePodCidr"
    assign_ipv4: true
    assign_ipv6: false
  kubeControllers:
    enabled: true
  typha:
    enabled: true
  ipv4:
    enabled: true
    pool: ipip # or vxlan
    mode: "Always"
    autoDetectionMethod: "first-found"
  ipv6:
    enabled: false
    pool: vxlan
    mode: "Never"
    autoDetectionMethod: "first-found"
    natOutgoing: true
  felix:
    ipinip:
      enabled: "true"
    bpf:
      enabled: "false"
    bpfKubeProxyIPTablesCleanup:
      enabled: "false"
  nonPrivileged: false
images:
  calico-node: "image-repository:image-tag"
  calico-cni: "image-repository:image-tag"
  calico-typha: "image-repository:image-tag"
  calico-kube-controllers: "image-repository:image-tag"
  calico-cpva: "image-repository:image-tag"
  calico-cpa: "image-repository:image-tag"

vpa:
  enabled: false
  node: false
  typha: false

pspDisabled: false
