{{- if and .Values.bgp.manage .Values.bgp.routeReflectors }}
---
# Workers (non-RRs) peer with all RRs.
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: peer-clients-to-rrs
spec:
  nodeSelector: "!has(route-reflector)"
  peerSelector: {{ .Values.bgp.routeReflectors.nodeSelector | quote }}
---
# RRs peer with each other (full mesh among RRs only).
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: peer-rr-to-rr
spec:
  nodeSelector: {{ .Values.bgp.routeReflectors.nodeSelector | quote }}
  peerSelector: {{ .Values.bgp.routeReflectors.nodeSelector | quote }}
{{- end }}