apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
    fluentbit.gardener.cloud/type: "seed"
  name: calico-node
spec:
  filters:
  - parser:
      keyName: log
      parser: calico-node-parser
      reserveData: true
  match: kubernetes.*calico-node*calico-node*
