apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterParser
metadata:
  name: calico-node-parser
  labels:
    fluentbit.gardener/type: "seed"
    fluentbit.gardener.cloud/type: "seed"
spec:
  regex:
    timeKey: time
    timeFormat: "%Y-%m-%d %H:%M:%S.%L"
    regex: '^(?<time>\d{4}-\d{2}-\d{2}\s+[^ ]*)\s+\[(?<severity>\w*)\]\[(?<pid>\d+)\]\s+(?<source>[^:]*):\s+(?<log>.*)'
