apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-networking-calico
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-networking-calico
    helm.sh/chart: gardener-extension-networking-calico
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-networking-calico
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.imageVectorOverwrite }}
      annotations:
        checksum/configmap-network-imagevector-overwrite: {{ include (print $.Template.BasePath "/configmap-imagevector-overwrite.yaml") . | sha256sum }}
      {{- end }}
      labels:
        app.kubernetes.io/name: gardener-extension-networking-calico
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      priorityClassName: gardener-extension-networking-calico
      serviceAccountName: gardener-extension-networking-calico
      containers:
      - name: gardener-extension-networking-calico
        image: {{ include "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-networking-calico
        - --leader-election-resource-lock={{ .Values.leaderElection.resourceLock }}
        - --max-concurrent-reconciles={{ .Values.controller.concurrentSyncs }}
        - --healthcheck-max-concurrent-reconciles={{ .Values.controller.healthcheck.concurrentSyncs }}
        - --ignore-operation-annotation={{ .Values.controller.ignoreOperationAnnotation }}
        - --config-file=/etc/{{ include "name" . }}/config/config.yaml
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.imageVectorOverwrite }}
        - name: IMAGEVECTOR_OVERWRITE
          value: /charts_overwrite/images_overwrite.yaml
        {{- end }}
        {{- if .Values.config.egressFilter.enabled }}
        - name: EGRESS_FILTER_ENABLED
          value: "true"
        - name: ALLOWED_TIME_IN_SECONDS_WITHOUT_EGRESS_LIST
          value: {{ .Values.config.egressFilter.maxTimeInSecondsUntilFirstDownload | quote }}
        {{- end }}
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | nindent 10 }}
{{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/{{ include "name" . }}/config
        {{- if .Values.imageVectorOverwrite }}
        - name: imagevector-overwrite
          mountPath: /charts_overwrite/
          readOnly: true
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "name" . }}-configmap
          defaultMode: 420
      {{- if .Values.imageVectorOverwrite }}
      - name: imagevector-overwrite
        configMap:
          name: {{ include "name" . }}-imagevector-overwrite
          defaultMode: 420
      {{- end }}
